- api/v1/Game.php
- composer-symfony5.4.json
- composer-symfony5.4.lock
- src/Domain/Helper/AsyncDatabase.php
- src/Domain/WsServer/WsServer.php
Revert "using the new "keep alive" strategy implemented in reactphp-dbal (#22)"
This reverts commit c2abcc1d33d8dc0f70194a61818146e8f3dd03a8.
> Revert "using the new "keep alive" strategy implemented in reactphp-dbal (#22)"

- config-symfony5.4/routes/tools.yaml
- src/Controller/LegacyController.php
- src/Domain/Common/CommonBase.php
* fixed _tools routing in production, should not be allowed.
* fixed Loop being created although there is no need for async. Caused loop to run indefinitely
> Some bug fixes

- install.sh
- tools/install-tools.sh
making sure that install.sh and install-tools.sh can work with some environmental variables. Need for InnoSetup
> making sure that install.sh and install-tools.sh can work with some environmental variables. Need for InnoSetup

- api/v1/Energy.php
* fixed bug with cast and operator order
* removed grouping on country id which will cause lost of data I think
> bugfix with updateEnergyGrid

- composer-symfony5.4.json
- composer-symfony5.4.lock
composer update with composer-git-hooks repo using BUAS github, not my personal github
> composer update with composer-git-hooks repo using BUAS github, not my personal github

- src/Domain/WsServer/WsServer.php
> MSP-3961 adds demo sessions on SETUP to WsServer tick monitoring

- api/v1/GameSession.php
- api/v1/Update.php
- public/.htaccess
> MSP-4000 fixes wrong var name and save path, moves max upload and post size config so they actually work

- api/v1/Base.php
- api/v1/User.php
- public/ServerManager/js/manager.gamesession.js
> MSP-4001 fixes MSP Challenge authentication provider

- ServerManager/classes/ServerManager.php
- api/v1/Update.php
> MSP-3890 also enables session db migrations from beta8 and beta9 to beta10

- src/Domain/WsServer/WsServer.php
> MSP-4002 makes WsServer track all simulable (simulation-able?) sessions

- ServerManager/configfiles/North_Sea_basic/North_Sea_basic_1.json
> MSP-3960 gets rid of unnecessary starting plan NS

- api/v1/Database.php
> MSP-4005 adds quotes to mysql app paths to deal with spaces in them

- api/v1/Store.php
> MSP-3953 turns type definition in source geodata into string again to support multitypes

- wsserver-win-service.bat
* when calling wsserver-win-service.bat it will retrieve the script path , and change the directory there
* on eof it set the director back to the working directory it was
> improved batch file directory handling

- src/Domain/WsServer/Plugins/AwaitPrerequisitesWsServerPlugin.php
do "select name from settings limit 1"  instead of select 1, to also check if data is present
> do "select name from settings limit 1"  instead of select 1, to also check if data is present

- api/v1/GameSession.php
port needs to be added for api root such that simulations connect to the correct url
> port needs to be added for api root such that simulations connect to the correct url

- api/v1/Game.php
- src/Command/WsServerCommand.php
- src/Domain/WsServer/Plugins/BootstrapWsServerPlugin.php
- src/Domain/WsServer/Plugins/Latest/LatestWsServerPlugin.php
* added payload dump feature
* added todo for division by zero I encoutered
* moved some lines in separate functions in Latest plugin
> feature payload dump

- src/Domain/WsServer/Plugins/Tick/GameTick.php
> MSP-4016 removes old, irrelevant, erroneous if statement

- ServerManager/classes/GameConfig.php
> MSP-4019 fixes three bugs in GameConfig class

- .env
- ServerManager/classes/GameSession.php
- ServerManager/configfiles/Adriatic_Sea_basic/Adriatic_Sea_basic_1.json
- ServerManager/configfiles/Baltic_Sea_basic/Baltic_Sea_basic_1.json
- ServerManager/configfiles/Clyde_marine_region_basic/Clyde_marine_region_basic_1.json
- ServerManager/configfiles/North_Sea_Digitwin_basic/North_Sea_Digitwin_basic_1.json
- ServerManager/configfiles/North_Sea_basic/North_Sea_basic_1.json
- api/v1/Game.php
> MSP-3712 also adds edition vars to ServerManager/api/getsessionslist.php

- composer-symfony5.4.lock
Just a "composer update" to get vendor software up-to-date
> MSP-4154 composer update

- ServerManager/classes/GameSession.php
> fixed phpstan error

- .github/workflows/php.yml
- composer-symfony5.4.json
- composer-symfony5.4.lock
- tools/cghooks-fresh-install.sh
> Githook phpstan

- .github/workflows/php.yml
> try to disable xdebug in workflow

- migrations/Version20230202120117.php
added migration to add an unique key to the plan_layer table on columns plan_layer_plan_id, plan_layer_layer_id
> MSP-4240 added migration to add an unique key to the plan_layer table on columns plan_layer_plan_id, plan_layer_layer_id

- ServerManager/configfiles/Adriatic_Sea_basic/Adriatic_Sea_basic_1.json
- ServerManager/configfiles/Baltic_Sea_basic/Baltic_Sea_basic_1.json
- ServerManager/configfiles/Clyde_marine_region_basic/Clyde_marine_region_basic_1.json
- ServerManager/configfiles/North_Sea_Digitwin_basic/North_Sea_Digitwin_basic_1.json
- ServerManager/configfiles/North_Sea_basic/North_Sea_basic_1.json
> MSP-4449 just copying the files

- wsserver-win-service.bat
first add websocket server firewall rule before actually installing and running it
> MSP-4443 Frst add websocket server firewall rule before actually installing and running it

- src/Domain/WsServer/Plugins/AwaitPrerequisitesWsServerPlugin.php
- src/Domain/WsServer/Plugins/BootstrapWsServerPlugin.php
- wsserver-win-service.bat
> MSP-4443: Release RC1

- api/v1/Plan.php
> MSP-4539 enables removal of restriction areas after initial definition

- api/v1/Game.php
> MSP-4637 fixes potential division by zero

- Dockerfile
- ServerManager/templates/footer.php
- docker-compose.yml
- docker/php/conf.d/app.ini
- public/ServerManager/js/manager.base.js
so this does not fix any jira issues at the moment. 
But it fixes the ability to update public files from the host , and that those files are linked into the container directly
It also fixed a console error, and a invalid path to an image in the ServerManager template when used from install.php
> add volume to public folder for both caddy and php container

- src/Repository/ServerManager/GameListRepository.php
> MSP-4721 adds trailing slash to game_server_address in /manager/gamelist

- ServerManager/configfiles/North_Sea_basic/North_Sea_basic_1.json
> MSP-4746 another copy-over from Private/ConfigFiles

- docker/php/docker-entrypoint.sh
- docker/supervisor/supervisor.d/msw.ini
> MSP-4748 removes /v1 from paths as they do not exist anymore

- install.sh
> MSP-4766 alters JWT keypair generation command when in Docker

- docker-compose.override.yml
> disabled mitmproxy, needs fixing for ws protocol

- Dockerfile
> force use xdebug 3.2 , since 3.3 seems to have issues

- install.sh
> fix openssl conf handling

- src/Controller/SessionAPI/GameController.php
> fix createpovconfig api fields

- src/Command/CreatePOVConfigCommand.php
- src/Domain/POV/ConfigCreator.php
> fixed issues with pov create config

- src/Controller/SessionAPI/GameController.php
- src/Domain/POV/ConfigCreator.php
* fixed layer data retrieval if it not an original one (so a child of a parent) -- for now assuming only one-level deep, so a single left join is enough
some small stuff:
* renamed a const var
* removed unused "use"
* fixed deprecation notice on fetch()
* fixed usage of Exception class
* added Content-Length to header
> POV-488 Fixes in the pov config creation code

- config-symfony5.4/packages/security.yaml
> make Game/CreatePOVConfig publicly accessible

- composer-symfony5.4.lock
> composer update

- ServerManager/configfiles/North_Sea_basic/North_Sea_basic_1.json
> update layer tags for NS

- docker-compose.hybrid.yml
- docker-compose.override.yml
- docker-compose.prod.yml
- docker-compose.yml
> Set php dev image name

- src/Entity/Layer.php
- src/EventListener/SessionEntityListener.php
- src/MessageHandler/GameList/GameListCreationMessageHandler.php
> MSP-4957 code tweak / clean-up

- docker/supervisor/supervisor.d/messenger-worker.ini
> MSP-4965 best to just go for root I think

- composer-symfony5.4.json
- composer-symfony5.4.lock
> composer does not require imagick anymore, but there is suggestion

- docker-compose.override.yml
- docker-compose.staging.yml
- docker-compose.yml
with these changes, when you do "docker inspect" or check the inspect tab in docker desktop. and search for "logconfig" you see the driver now is set to local for all containers
> set docker driver local for each container

- ServerManager/configfiles/Eastern_Med_Sea_basic/Eastern_Med_Sea_basic_1.json
- api/v1/Store.php
- src/Entity/Geometry.php
* Handle map_type ranges only if there are 2 numbers
* set the fifth map_type value to "other" for the layer "Quality of Bathing Waters"
> MSP-5439 handle map_type ranges only if there are 2 numbers

- .github/workflows/php.yml
- .gitignore
- .php-cs-fixer.dist.php
- Dockerfile
- composer-symfony6.4.json
- composer-symfony6.4.lock
- docker-aliases.sh
- docker-compose.adminer.yml
- docker-compose.override.yml
- docker-compose.prod.yml
- docker-compose.staging.yml
- docker-compose.yml
- docker/adminer/adminer.css
- docker/adminer/index.php
- symfony6.4.lock
* composer update
* keep command history inside of php container
* project name for docker composer is not postfix by the environment name (dev,staging or prod)
* in the docker compose yaml we use container_name instead of image. image causes the side-effect of docker compose trying to actual fetch the image from the online docker repository.
* using adminerevo
* on dev the database port is exposed , to allow external connections , e.g. mysql workbench
* we use *.ini wildcard now for supervisor conf files
* removed adminer container configuration duplication by moving it to its own file (and alias commands have been changed to include it)
> various dev improvements

- ServerManager/configfiles/Adriatic_Sea_basic/Adriatic_Sea_basic_1.json
- api/v1/Plan.php
- migrations/Version20200101000000.php
> Release bug fixes

- README.md
- frankenphp/docker-entrypoint.sh
* bash install.sh to symlink config folder and all before calling set facl on them
* update readme
> docker-entrypoint fix + readme update

- frankenphp/docker-entrypoint.sh
- src/Controller/HomeController.php
* do setfacl if files already exist before calling bash install.sh
> * create public/downloads folder if it does not exist

- ServerManager/configfiles/Eastern_Med_Sea_basic/Eastern_Med_Sea_basic_1.json
> ems fleet id fix

- config-symfony6.4/packages/security.yaml
- config-symfony7.2/packages/security.yaml
> fixes security issue when using /ServerManager rather than /manager

- src/MessageHandler/GameList/CommonSessionHandlerBase.php
- src/MessageHandler/GameList/GameListArchiveMessageHandler.php
- src/MessageHandler/GameSave/GameSaveCreationMessageHandler.php
> Fixes to messagehandler bugs

- assets/controllers/gamelist_controller.js
- docker-aliases.sh
- frankenphp/docker-entrypoint.sh
- src/Controller/ServerManager/GameListController.php
- templates/manager/GameList/gamelist_details.html.twig
* suppress output from "php docker/export-dotenv-vars/app.php"
* disabling verbose mode for doctrine migrations in docker-entrypoint.sh
* added button to connect watchdog to session
> added button to connect watchdog to session

- migrations/Version20241128170458.php
- src/Controller/SessionAPI/GameController.php
- src/Controller/SessionAPI/SimulationController.php
- src/Controller/SessionController.php
- src/EventListener/AccessTokenAuthenticatedListener.php
- src/Repository/ServerManager/GameListRepository.php
* support both /api/game and /api/Game
* if session database does not exist report a 410 . If the session is unhealthy report a 513 http code
* set default values for players_active and players_last_hour to zero if null
* check if MEL/SEL keys are set before inserting default values
> various bug fixes

- src/Controller/SessionAPI/UserController.php
check and force country_id field to be an integer
> check and force country_id field to be an integer

- api/v1/Game.php
- api/v1/GameSession.php
- api/v1/User.php
This solves a problem I caused when I reprogrammed the Server Manager.
It also presents a next small step towards getting rid of some of the old custom API classes, particularly GameSession.
> Custom passwords fix
