api/v1/class.layer.php

Makes necessary (but presumably temporary) changes to server API's layer class to turn 0.0 values of layer_entity_value_max into null. At some point in the future the CradleConfigEditor will be able to handle setting null values to floats, at which point we will have a neater solution.

layer_entity_value_max: turns 0.0 into null

---

src/Domain/WsServer/WsServer.php
src/Domain/WsServer/WsServerConsoleHelper.php

* fixed typo
* LATEST_CLIENT_UPDATE_SPEED changed from 1 to 60s

Far lesser update required if client has its own timer count down see https://github.com/BredaUniversityResearch/MSPChallenge-Client/pull/38

---

composer-symfony5.4.json
composer-symfony5.4.lock

removed usage of our own fork of reactphp-dbal, since it has been merged to the origin. yeah!
Nice to be part of the project:
[* https://github.com/marinhekman/reactphp-dbal/commit/fd55f3a16d4b526dcbcc525407089d3d500179a9](https://github.com/driftphp/reactphp-dbal/commit/fd55f3a16d4b526dcbcc525407089d3d500179a9)

removed fork, using origin now

---

.github/workflows/php.yml
composer-symfony5.4.json
composer-symfony5.4.lock
symfony5.4.lock
test.sh
tools/install-tools.sh

* removed unused php tool "php mess dectector"
* added php code sniffer using composer.json , now required on dev. It can be *automatically used* by your editor, e.g. phpstorm . So, far more easier setup. After composer install vendor/bin will hold phpcs and phpcbf working for both Windows and Linux
* I kept the other one which we download ourselves using install-tools.sh as well since that one it easier to use from Github work-flow since it has no composer dependency.

added another phpcs (code sniffer) through composer for easy setup with your editor (automatic)

---

composer-symfony5.4.json
composer-symfony5.4.lock

So this is experimental, but needs to be merged to see if it works unfortenately since it triggered by merges.
What is changed? 
It just uses our own fork of the composer-git-hooks vendor.
In that fork we improved some error handling when files are not writtable, and what should happen on a "forcing add of a hook". So no more php warnings if file cannot be written, but just show an appropiate error.
And another change is: we allow to say: "file hook is up to date" and do not continue with the add of a hook when it is FORCED. This will prevent issues during merge if the file hooks are already present, which is the case normally speaking.
So lets test and merge this, if it works I will contribute the changes to the origin hub if they want it..
See: …

Handle composer git hooks file permission denied

---

src/Domain/WsServer/Plugins/Tick/TickWsServerPlugin.php
src/Domain/WsServer/ServerManagerInterface.php
src/Domain/WsServer/WsServer.php

* only retieve the game session ids that are "healthy"
* added option to only retrieve game session ids "playing" which are the game states: play, fastforward and simulation
* remove doDummyQuery call in "registerLoop", does not exist anymore. Is now handled by DriftPHP itself using "keep alive", see ConnectionPoolOptions class

fix for the "healthy" retrieving game session ids, and/or only the "playing" ones. Removed usage of doDummyQuery.

---

composer-symfony5.4.json
composer-symfony5.4.lock

composer update along with a switch to another driftphp-dbal "buas" branch. 
This allows us to have our own forks being used until these are merged to the origin. This "buas" branch has been merged with multiple branches: connection-keep-alive and fix-deprecations

composer update

---

api/v1/Update.php
src/Domain/Common/CommonBase.php

so I tested "From40beta7To40beta10" using the URL
http://localhost/1/api/update/From40beta7To40beta10
with a small code modification (changed Security::ACCESS_LEVEL_FLAG_SERVER_MANAGER to
Security::ACCESS_LEVEL_FLAG_NONE)
Bug-fixes:
* improved the error message when you call the api without specifying the game session id. e.g. /api/.. instead of /1/api/..
* caught the "duplicate column" dpo error exception. Calling From40beta7To40beta9 will through this error if you have already migrated to beta8 or -9 already. Which is bad, since that would prevent the further migration to beta10. With this fix From40beta7To40beta10 can be called from beta7-9 and the database will be migrated to beta 10 .
* little feature: added the result of a succeeded migration. So this will be part of the api payload …

Tested and fixed using From40beta7To40beta10 api call

---

bin/migrations
src/Command/WsServerCommand.php
src/Domain/Services/DoctrineMigrationsDependencyFactoryHelper.php
src/Domain/WsServer/Plugins/BootstrapWsServerPlugin.php
src/Domain/WsServer/Plugins/Plugin.php
src/Domain/WsServer/ServerManagerInterface.php
src/Domain/WsServer/WsServer.php

* added new BootstrapWsServerPlugin for the websocket server, which:
- detect the need for database migrations, and applies them;
- after the migrations if will register the other plugins: tick, latest etc
* created a service DoctrineMigrationsDependencyFactoryHelper which is used by both the  console bin/migrations and by BootstrapWsServerPlugin
* Extend Plugin class to allow zero value for minIntervalSec, in which case it will only run the plugin once (no interval)

run a migrations on websocket server start

---

ServerManager/classes/Base.php
ServerManager/classes/DB.php
ServerManager/classes/ServerManager.php
ServerManager/classes/Token.php
ServerManager/classes/User.php
ServerManager/helpers.php
ServerManager/login.php
api/v1/Batch.php
api/v1/mysql_structure.sql
composer-symfony5.4.json
migrations/Version20211208135721.php
migrations/Version20220413200747.php
migrations/Version20220607114759.php
migrations/src/MSPMigration.php
src/Command/WsServerCommand.php
src/Domain/Common/Enum.php
src/Domain/Common/GetConstantsTrait.php
src/Domain/Helper/Config.php
src/Domain/WsServer/Plugins/ExecuteBatchesWsServerPlugin.php
src/Domain/WsServer/WsServer.php
src/Domain/WsServer/WsServerInterface.php

demo of this fix:
[one drive video](https://edubuas-my.sharepoint.com/:v:/g/personal/hekman_m_buas_nl/EQyL3nJ9of5AokpFDU2jP9MBNrOq5HOTRTgdkZD8170-nA?e=dQMJ1y)
how it looks like after the demo in the database api_batch table:
* Moved Config.php from ServerManager/classes to src/Domain/Helper such that it can be used from the websocket server as well as the server manager side
* Added websocket server id. It can be passed as a console argument, if not, the default would be the scheme+address+port.
* Implemented a doctrine migration file to add api_batch_server_id, api_batch_communicated columns to api_batch table.
* Pass the websocket server id to Batch::executeNextQueuedBatchFor and ::executeQueuedBatch call such that it can be stored in the database to api_batch.api_batch_server_id
* …

Recovery after crash during executing batch

---

src/Domain/WsServer/Plugins/AwaitPrerequisitesWsServerPlugin.php
src/Domain/WsServer/Plugins/BootstrapWsServerPlugin.php
src/Domain/WsServer/Plugins/DatabaseMigrationsWsServerPlugin.php
src/Domain/WsServer/Plugins/ExecuteBatchesWsServerPlugin.php
src/Domain/WsServer/Plugins/Latest/GameLatest.php
src/Domain/WsServer/Plugins/Latest/LatestWsServerPlugin.php
src/Domain/WsServer/Plugins/Plugin.php
src/Domain/WsServer/Plugins/PluginHelper.php
src/Domain/WsServer/Plugins/Tick/GameTick.php
src/Domain/WsServer/Plugins/Tick/TickWsServerPlugin.php
src/Domain/WsServer/WsServerOutput.php
src/Domain/WsServer/functions.php

normal level: (no arguments, the default)
- shows one-time messages like: migrating... server ready
verbose level: (-v or --verbose)
- shows all communications, like client connections, all content messages etc
(This will be mostly used on dev environments. You can set .env file with WS_SERVER_OUTPUT_VERBOSITY=64)
very verbose level: (-vv or -vvv)
- shows flows, like starting tick, finished tick, that kind. Any repetitive stuff
needed for beta10 such that it does not output so much by default

fixed output verbosity

---

api/v1/Warning.php

send all layer issues back when Warning::Post() is called, not just the added ones

send all layer issues back when Warning::Post() is called, not just the added ones

---

ServerManager/api/addGameSession.php
ServerManager/api/browseGeoServer.php
ServerManager/api/editGameSession.php
ServerManager/api/editServerManager.php
ServerManager/classes/Base.php
ServerManager/classes/GameSession.php
ServerManager/classes/GeoServer.php

Issue was an endless loop calling getJWT:
* removed setJWT() , and the jwt property of GameSession class. Just store and get the token from the session using Session::get / ::put
* added hasJWT().
* the actual fix in Base::callAuthoriser: only call getJWT is hasJWT is true to prevent endless loop. E.g. getJWT calls postCallAuthoriser with "login_check" calling callAuthoriser, so callAuthoriser should not call getJWT if there is no token

MSP-4528 fix recreate game session on end state in demo mode

---

api/v1/GameSession.php

fixes usage of wrong http scheme with port 443 based on env variables. 
(went wrong for websocket server on production)

fix url scheme based on env variable URL_WEB_SERVER_SCHEME

---

api/v1/Game.php
api/v1/GameSession.php
config-symfony5.4/routes/web_profiler.yaml
config-symfony5.4/services.yaml
src/DataCollector/MSPDataCollector.php
templates/data_collector/msp.html.twig

such that you can just start the simulations for the current game session state, so without the need to change the game session state

added a "start simulations" button to the Symfony web profiler bar in the MSP section

---

Dockerfile

quick fix caddy: Temporary fix for https://github.com/dunglas/mercure/issues/770

quick fix caddy: Temporary fix for https://github.com/dunglas/mercure/issues/770

---

api/v1/Game.php

Fixes issue MSP-4605 , see `$log->setAsync(true);`

fixed "todo": do another watchdog alive test, with a repeat and failure mechanism

---

docs/xdebug.md

Fix small issue in documentation for setting up XDebug where the port needed to be 80 but was specified as 443.

Update XDebug documentation to use the right port

---

docker-aliases.sh
docker-compose.hybrid.yml

added another docker compose configuration called "hybrid" which is copied from the production one with the additional volume mapping taken from "override" (=dev).
So changing files in /srv/app will be directly linked ,there is no need to rebuild the image and container

added docker-compose.hybrid.yml which is the same as .prod.yml but with volume mapping on the root directory

---

src/Domain/POV/ConfigCreator.php

* Bug-fix: when excluding layers , the array needs to be re-indexed
* Clean-up: Removed "Bathymetry" copy
* Moved code lines in more methods for readability.
* Added linear grouped scale based on type names.
* The "max" scale is changed since the last type mapping need to be larger.
* moved "normaliseAndExtendRasterMappings" from "extractRegionFromRasterLayers" into its own method .
* normaliseAndExtendRasterMappings() should be called before fixMissingRasterLayerScales()

More POV create config improvements

---

docker-compose.prod.yml
docker-compose.staging.yml
docker-compose.yml

HTTP needs to be defined in the override/prod/staging/... yml files to prevent dev error: Bind for 0.0.0.0:80 failed: port is already allocated
this is because both the base and the override (dev) yml were defining a port 80

docker desktop bug-fix

---

frankenphp/Caddyfile

allow http://php:80 , which are internal http connections. so even on prod

allow http://php:80 , which are internal http connections. so even prod

---

docker-compose.override.yml
docker-compose.prod.yml
docker-compose.yml

* presist database content among re-creation of a container
* for prod only mount folders that have persistent data
* for dev there is no need to mount the cache or log folder by default.

Improved docker container setup for persistent data

---

src/MessageHandler/Watchdog/WatchdogCommunicationMessageHandler.php

- so *not* using host.docker.internal which fails if you do not use Docker Desktop - e.g. linux on prod
- disadvantage: no simulation communication monitoring with mitmproxy for now.

force simulations to communicate with http://php:80.
